# START WITH AN UBUNTU BASE
FROM ubuntu

# UPDATE APT-REG
RUN apt update -y

# INSTALL NODEJS, NPM & PYTHON3
RUN apt install nodejs -y
RUN apt install npm -y

# INSTALL REACT
RUN npm install -g create-react-app

# GOTO VIRTUAL WORK DIR
WORKDIR /project

# INSTALL & AUDIT DEPENDENCIES, THEN LAUNCH THE APP
CMD npm install && npm start