# START WITH AN UBUNTU BASE -- ARE THERE BETTER OPTIONS?
FROM ubuntu

# UPDATE APT-REG
RUN apt update -y

# INSTALL LINUX PREREQUISITS
RUN apt install python3 -y
RUN apt install python3-pip -y
RUN apt install ipython3 -y

# INSTALL NOTEBOOK STUFF -- NBC UPGRADE PREVENTS CRASHES
RUN pip3 install jupyter
RUN pip3 install --upgrade nbconvert

# INSTALL PYTHON LIBRARIES
RUN pip3 install web3
RUN pip3 install nbimporter

# GOTO VIRTUAL WORK DIR
WORKDIR /notebooks

# LAUNCH GETH OVER WEBSOCKET
CMD jupyter notebook \
    --port=8888 \
    --ip=0.0.0.0 \
    --no-browser \
    --allow-root \