# START WITH AN UBUNTU BASE
FROM ubuntu

# UPDATE APT-REG
RUN apt update -y

# INSTALL NODEJS, NPM & PYTHON3
RUN apt install nodejs -y
RUN apt install npm -y
RUN apt install python3 -y

# INSTALL THE TRUFFLE FRAMEWORK
RUN npm install -g truffle

# LET TRUFFLE DOWNLOAD & CACHE A SOLIDITY COMPILER
RUN truffle obtain --solc=0.8.4

# COPY RESOURCES OVER
ADD resources resources

# GOTO VIRTUAL WORK DIR
WORKDIR /project

# LAUNCH GETH OVER WEBSOCKET
CMD ../resources/migrate.sh